sudo: required
language: node_js
node_js:
  - "10"
before_script:
  - npm install -g karma-cli
  - npm install --save-dev karma karma-ui5
  - npm install --save-dev karma-chrome-launcher
script: karma start